# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Thiết lập linkage mặc định hoặc từ Environment
linkage = ENV['USE_FRAMEWORKS'] || 'static'

target 'aka_banking' do
  config = use_native_modules!
  
  # SỬA TẠI ĐÂY: Sử dụng frameworks nhưng liên kết tĩnh (static) 
  # Điều này giúp CleverTap (Swift) chạy được mà không làm hỏng lõi C++ của React Native
  use_frameworks! :linkage => linkage.to_sym
  
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

target 'nse' do
    use_frameworks! :linkage => linkage.to_sym
    pod 'CTNotificationService'  
end

target 'nce' do
    use_frameworks! :linkage => linkage.to_sym
    pod 'CleverTap-iOS-SDK'
    pod 'CTNotificationContent'  
end 